apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-k8s-stateful-postgres
  labels:
    app: hello-k8s-stateful
    tier: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  